############################################################
# Project : Smart ERP Billing System
#
# File    : queries.py
#
# Team Member :
# Team Member 5
#
# Module :
# Database & Integration
#
# Responsibilities :
# - SQLite
# - CRUD Operations
# - Database Integration
# - Validation
# - Testing
#
# Developed By :
# Team Member 5
############################################################
"""
File: queries.py

Purpose:
Acts as a Data Access Object (DAO) for the application. It centralizes all SQL queries 
(INSERT, SELECT, UPDATE, DELETE) so that the rest of the application doesn't have to write raw SQL.

Dependencies:
- database.connection (For executing the SQL queries)

Project: Smart ERP Billing System
"""

###########################################################
# Team Member 5
# Module: Database & Integration
# Completed:
# - SQLite
# - CRUD Operations
# - Database Integration
# - Validation
# - Testing
###########################################################
from database.connection import DatabaseConnection

# This class encapsulates all database queries into reusable methods.
# It solves the problem of scattering raw SQL strings throughout the GUI and Services,
# which makes code hard to maintain and prone to security vulnerabilities.
# Its responsibility is purely executing CRUD operations safely against the database.
# ---------------------------------------------
# Team Member 5
# Class: DatabaseQueries
# Purpose:
# Central repository for all SQL queries used by the Smart ERP.
# ---------------------------------------------
class DatabaseQueries:
    """
    Central repository for all SQL queries used by the Smart ERP.
    """
    
    # ---------------------------------------------
    # Team Member 5
    # Function: __init__
    # Purpose:
    # Handles logic for   init  
    # ---------------------------------------------
    def __init__(self):
        # Initialize the database connection once when the class is instantiated
        self.db = DatabaseConnection()

    # -------------------------------------------------------------------------
    # USER QUERIES
    # -------------------------------------------------------------------------
    
    # Purpose: Retrieves a user record given a username for authentication.
    # Parameters: username (str)
    # Returns: sqlite3.Row object if found, else None
    # ---------------------------------------------
    # Team Member 5
    # Function: get_user_by_username
    # Purpose:
    # Fetches a user from the database by their unique username.
    # ---------------------------------------------
    def get_user_by_username(self, username):
        """
        Fetches a user from the database by their unique username.
        """
        # We use parameterization (?) to prevent SQL Injection
        return self.db.fetchone("SELECT * FROM users WHERE username = ?", (username,))
    
    # Purpose: Registers a new user employee into the system.
    # ---------------------------------------------
    # Team Member 5
    # Function: create_user
    # Purpose:
    # Inserts a new user record.
    # ---------------------------------------------
    def create_user(self, username, password_hash, role):
        """
        Inserts a new user record.
        """
        # execute() returns the cursor, and lastrowid gives us the new ID generated by AUTOINCREMENT
        return self.db.execute(
            "INSERT INTO users (username, password_hash, role) VALUES (?, ?, ?)",
            (username, password_hash, role)
        ).lastrowid

    # -------------------------------------------------------------------------
    # COMPANY QUERIES
    # -------------------------------------------------------------------------
    
    # Purpose: Retrieves the primary company profile. Default ID is 1.
    # ---------------------------------------------
    # Team Member 5
    # Function: get_company
    # Purpose:
    # Fetches company profile settings.
    # ---------------------------------------------
    def get_company(self, company_id=1):
        """
        Fetches company profile settings.
        """
        return self.db.fetchone("SELECT * FROM companies WHERE id = ?", (company_id,))

    # Purpose: Updates or creates the company profile.
    # ---------------------------------------------
    # Team Member 5
    # Function: save_company
    # Purpose:
    # Upserts (Updates or Inserts) the company settings.
    # ---------------------------------------------
    def save_company(self, name, gst_number, address, phone, email, logo_path, company_id=1):
        """
        Upserts (Updates or Inserts) the company settings.
        """
        # First check if the company record already exists in the database
        existing = self.get_company(company_id)
        
        if existing:
            # If it exists, UPDATE the existing row
            self.db.execute('''
                UPDATE companies 
                SET name=?, gst_number=?, address=?, phone=?, email=?, logo_path=?
                WHERE id=?
            ''', (name, gst_number, address, phone, email, logo_path, company_id))
        else:
            # If it doesn't exist, INSERT a fresh new row
            self.db.execute('''
                INSERT INTO companies (id, name, gst_number, address, phone, email, logo_path)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            ''', (company_id, name, gst_number, address, phone, email, logo_path))

    # -------------------------------------------------------------------------
    # GENERIC QUERIES (Reusable for any table)
    # -------------------------------------------------------------------------
    
    # Purpose: Grabs all records from a specified table.
    # ---------------------------------------------
    # Team Member 5
    # Function: get_all
    # Purpose:
    # Retrieves all rows from a given table.
    # ---------------------------------------------
    def get_all(self, table_name):
        """
        Retrieves all rows from a given table.
        """
        # Note: We use string formatting (f-string) here for the table name because 
        # SQLite parameters (?) do not work for table names, only for values.
        # This is safe as long as table_name is hardcoded in the app and not user input.
        return self.db.fetchall(f"SELECT * FROM {table_name}")

    # Purpose: Fetches a single record by its primary key ID.
    # ---------------------------------------------
    # Team Member 5
    # Function: get_by_id
    # Purpose:
    # Retrieves a single row by ID.
    # ---------------------------------------------
    def get_by_id(self, table_name, record_id):
        """
        Retrieves a single row by ID.
        """
        return self.db.fetchone(f"SELECT * FROM {table_name} WHERE id = ?", (record_id,))

    # Purpose: Deletes a specific row by its ID.
    # ---------------------------------------------
    # Team Member 5
    # Function: delete_by_id
    # Purpose:
    # Deletes a row by ID.
    # ---------------------------------------------
    def delete_by_id(self, table_name, record_id):
        """
        Deletes a row by ID.
        """
        self.db.execute(f"DELETE FROM {table_name} WHERE id = ?", (record_id,))

    # -------------------------------------------------------------------------
    # CUSTOMER QUERIES
    # -------------------------------------------------------------------------
    
    # Purpose: Finds customers matching a specific search keyword.
    # ---------------------------------------------
    # Team Member 5
    # Function: search_customers
    # Purpose:
    # Searches the customer table across multiple columns.
    # ---------------------------------------------
    def search_customers(self, search_term):
        """
        Searches the customer table across multiple columns.
        """
        # The % wildcards tell SQL to match the term anywhere inside the string (LIKE query)
        term = f"%{search_term}%"
        return self.db.fetchall('''
            SELECT * FROM customers 
            WHERE name LIKE ? OR phone LIKE ? OR email LIKE ? OR gst_number LIKE ?
        ''', (term, term, term, term))

    # Purpose: Inserts a new customer into the DB.
    # ---------------------------------------------
    # Team Member 5
    # Function: add_customer
    # Purpose:
    # Adds a new customer.
    # ---------------------------------------------
    def add_customer(self, name, phone, email, gst, address):
        """
        Adds a new customer.
        """
        return self.db.execute(
            "INSERT INTO customers (name, phone, email, gst_number, address) VALUES (?, ?, ?, ?, ?)",
            (name, phone, email, gst, address)
        ).lastrowid

    # -------------------------------------------------------------------------
    # PRODUCT QUERIES
    # -------------------------------------------------------------------------
    
    # Purpose: Inserts a new product into the inventory system.
    # ---------------------------------------------
    # Team Member 5
    # Function: add_product
    # Purpose:
    # Adds a new product to inventory.
    # ---------------------------------------------
    def add_product(self, name, category, hsn, cost, selling, gst, stock, supplier_id):
        """
        Adds a new product to inventory.
        """
        return self.db.execute('''
            INSERT INTO products (name, category, hsn_code, cost_price, selling_price, gst_percentage, stock_quantity, supplier_id)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ''', (name, category, hsn, cost, selling, gst, stock, supplier_id)).lastrowid

    # ---------------------------------------------
    # Team Member 5
    # Function: search_products
    # Purpose:
    # Searches the product table.
    # ---------------------------------------------
    def search_products(self, search_term):
        """
        Searches the product table.
        """
        term = f"%{search_term}%"
        return self.db.fetchall('''
            SELECT * FROM products 
            WHERE name LIKE ? OR category LIKE ? OR hsn_code LIKE ?
        ''', (term, term, term))

    # -------------------------------------------------------------------------
    # INVENTORY & BILLING QUERIES
    # -------------------------------------------------------------------------
    
    # Purpose: Updates the stock count for a product and logs the adjustment.
    # ---------------------------------------------
    # Team Member 5
    # Function: update_stock
    # Purpose:
    # Adjusts inventory levels safely.
    # ---------------------------------------------
    def update_stock(self, product_id, quantity_change, user_id, reason="Invoice Creation"):
        """
        Adjusts inventory levels safely.
        """
        # We use 'stock_quantity = stock_quantity + ?' so the database handles the math safely, avoiding race conditions.
        self.db.execute("UPDATE products SET stock_quantity = stock_quantity + ? WHERE id = ?", (quantity_change, product_id))
        
        # Log the change into the audit table for tracking history.
        self.db.execute(
            "INSERT INTO inventory_logs (product_id, change_amount, reason, created_by) VALUES (?, ?, ?, ?)",
            (product_id, quantity_change, reason, user_id)
        )

    # ---------------------------------------------
    # Team Member 5
    # Function: create_invoice
    # Purpose:
    # Creates a new invoice record.
    # ---------------------------------------------
    def create_invoice(self, data):
        """
        Creates a new invoice record.
        """
        # Validate that the requested company actually exists to prevent foreign key constraint failures
        company_id = data.get('company_id', 1)
        if not self.get_company(company_id):
            company_id = None
            
        # We extract data from the incoming dictionary safely using .get() to prevent KeyError on missing optional fields.
        cursor = self.db.execute('''
            INSERT INTO invoices (
                invoice_number, customer_id, company_id, subtotal, discount, 
                cgst, sgst, igst, total_tax, total_amount, payment_method, 
                status, amount_paid, notes, created_by, qr_hash
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            data['invoice_number'], data.get('customer_id'), company_id,
            data['subtotal'], data.get('discount', 0), data.get('cgst', 0),
            data.get('sgst', 0), data.get('igst', 0), data.get('total_tax', 0),
            data['total_amount'], data.get('payment_method'), data.get('status', 'Pending'),
            data.get('amount_paid', 0), data.get('notes', ''), data.get('created_by'), data.get('qr_hash', '')
        ))
        # Return the new Invoice ID so we can link the InvoiceItems to it in the next step.
        return cursor.lastrowid

    # Purpose: Attaches a sold product item to a specific invoice.
    # ---------------------------------------------
    # Team Member 5
    # Function: add_invoice_item
    # Purpose:
    # Adds a line item to an existing invoice.
    # ---------------------------------------------
    def add_invoice_item(self, invoice_id, item):
        """
        Adds a line item to an existing invoice.
        """
        self.db.execute('''
            INSERT INTO invoice_items (invoice_id, product_id, quantity, price, discount, gst_percentage, total)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (
            invoice_id, item['product_id'], item['quantity'], item['price'], 
            item.get('discount', 0), item['gst_percentage'], item['total']
        ))

    # ---------------------------------------------
    # Team Member 5
    # Function: update_invoice_status
    # Purpose:
    # Updates the payment status of an invoice.
    # ---------------------------------------------
    def update_invoice_status(self, invoice_number, new_status):
        """
        Updates the payment status of an invoice.
        """
        self.db.execute("UPDATE invoices SET status = ? WHERE invoice_number = ?", (new_status, invoice_number))


    # Purpose: Creates a generic audit log entry.
    # ---------------------------------------------
    # Team Member 5
    # Function: log_audit
    # Purpose:
    # Records a system action for audit purposes.
    # ---------------------------------------------
    def log_audit(self, user_id, action, target_type=None, target_id=None, details=None):
        """
        Records a system action for audit purposes.
        """
        self.db.execute('''
            INSERT INTO audit_logs (user_id, action, target_type, target_id, details)
            VALUES (?, ?, ?, ?, ?)
        ''', (user_id, action, target_type, target_id, details))
